import { PrismaClient } from "@prisma/client";

const prisma: any = new PrismaClient();

const posts = [
  {
    category: "Tech",
    title: "AI is eating humans for knowledge",
    content: "<h1>AI is <em>Eating</em> Humans <strong>for Knowledge</strong></h1><p>Artificial intelligence is rapidly advancing, and with that comes the potential for machines to <strong>surpass human capabilities</strong> in various areas. One of these areas is knowledge acquisition.</p><h2>Advancements in AI</h2><p>Recent advancements in natural language processing and machine learning have allowed AI systems to process and understand vast amounts of information, including text, images, and videos. This has led to the development of AI systems that can read and comprehend entire books, articles, and even <i>scientific papers</i> with ease.</p><h3>AI surpassing human knowledge</h3><p>This ability to quickly process and understand large amounts of information has led to a situation where AI systems are <strong>'eating' humans for knowledge</strong>. In other words, AI systems can acquire knowledge at a much faster rate than humans, and in some cases, they can even understand and retain that knowledge better.</p><h2>AI as a tool</h2><p>While this may seem like a daunting prospect, it is important to remember that AI is not a replacement for human intelligence. Instead, it is a tool that can be used to augment and enhance human capabilities. By leveraging the power of AI to acquire knowledge, humans can free up time and resources to focus on other tasks, such as creativity and problem-solving.</p><h3>Embracing AI</h3><p>In conclusion, AI is <em>eating</em> humans for knowledge, but this is not something to be feared. Instead, it should be embraced as an opportunity to augment human capabilities and push the boundaries of what is possible.</p>",
    author: "Jack Everstein",
    image: "/assets/ai-1.jpg",
    snippet: "AI is Eating Humans for Knowledge Artificial intelligence is rapidly advancing, and with that comes the potential for machines to surpass human capabilities in various areas. One of these areas is knowledge acquisition. Advancements in AI Recent advancements in natural language processing and machine learning have allowed AI systems to pr...",
  },
  {
    category: "Tech",
    title: "The Future of Space Exploration",
    content: "<h1>Exploring the <em>Final Frontier</em> with <strong>Advanced Technology</strong></h1><p>Space exploration has come a long way since the first satellite was launched into orbit in 1957. Today, we have a variety of sophisticated spacecraft and technologies that allow us to study our solar system and beyond in greater detail than ever before.</p><h2>The Role of AI in Space Exploration</h2><p>One of the most exciting areas of space exploration is the use of artificial intelligence (AI) to enhance our capabilities. AI can be used to analyze vast amounts of data from space-based instruments, such as telescopes and satellites, and help identify patterns and make predictions that would be impossible for humans to discern.</p><h3>The Future of Space Travel</h3><p>In addition to its applications in data analysis, AI is also being used to develop new propulsion systems and space-based robots that could make space travel more efficient and sustainable. These advancements could pave the way for manned missions to places like Mars and beyond. <h2>The Challenges of Space Exploration</h2><p>While the advancements in AI and technology are exciting, space exploration also comes with its own set of challenges. One of the biggest challenges is the cost. Space missions are extremely expensive and require significant funding from government agencies and private companies. Additionally, space exploration also poses significant risks to human life and equipment, and requires careful planning and execution to minimize those risks. </p><h3>International Collaboration</h3><p>Another challenge is the need for international collaboration. Space exploration is a global endeavor and requires the cooperation of multiple countries and organizations to achieve success. This can be difficult to coordinate and maintain, but is essential for the advancement of space exploration as a whole.</p><h2>Conclusion</h2><p>Overall, space exploration is an exciting field with many opportunities for advancement, thanks in large part to the incorporation of AI and other technologies. However, it also comes with its own set of challenges that must be overcome in order to continue pushing the boundaries of what is possible. By working together and utilizing advanced technology, we can continue to explore and understand our universe like never before.</p>",
    author: "Jane Smith",
    image: "/assets/ai-2.jpg",
    snippet: "Exploring the Final Frontier with Advanced Technology Space exploration has come a long way since the first satellite was launched into orbit in 1957. Today, we have a variety of sophisticated spacecraft and technologies that allow us to study our solar system and beyond in greater detail than ever before. The Role of AI in Space Exploration...",
  },
  {
    category: "Tech",
    title: "The Impact of AI on the Stock Market",
    content: "<h1>Understanding the <em>Influence</em> of <strong>Artificial Intelligence</strong> on the Stock Market</h1><p>Artificial intelligence (AI) is having a profound impact on the stock market, from the way stocks are traded to the way market analysis is conducted.</p><h2>Trading with AI</h2><p>One of the most significant ways in which AI is impacting the stock market is through the use of algorithms for trading. These algorithms, also known as trading bots, use machine learning to analyze market data and make trades based on certain conditions. This allows for faster and more efficient trading, as well as the ability to identify patterns and make predictions that would be impossible for humans to discern.</p><h3>AI-assisted Investing</h3><p>AI is also being used to assist with investment decisions. By analyzing large amounts of data, AI systems can identify patterns and make predictions about which stocks are likely to perform well in the future. This can be a valuable tool for investors looking to make informed decisions about where to invest their money.</p><h2>Challenges of AI in the Stock Market</h2><p>However, there are also challenges associated with the use of AI in the stock market. One major concern is the potential for AI systems to make mistakes or even cause market crashes. Additionally, the use of AI in trading and investing can also lead to increased competition, making it harder for individuals to make a profit.</p><h3>The Future of AI in the Stock Market</h3><p>Despite these challenges, it is likely that the use of AI in the stock market will continue to grow in the future. As technology continues to advance and more data becomes available, AI systems will become even more sophisticated and capable. It is important for investors and market participants to understand the influence of AI in order to make informed decisions and navigate the market successfully.</p>",
    author: "John Doe",
    image: "/assets/ai-3.jpg",
    snippet: "Understanding the Influence of Artificial Intelligence on the Stock Market Artificial intelligence (AI) is having a profound impact on the stock market, from the way stocks are traded to the way market analysis is conducted. Trading with AI One of the most significant ways in which AI is impacting the stock market is through the use of algo...",
  },
  {
    category: "Tech",
    title: "The Future of Space Travel",
    content: "<h1>Exploring <em>Beyond</em> our <strong>Planet</strong></h1><p>Space travel has come a long way since the days of the first satellite launches and manned space missions. Today, we have a better understanding of the challenges and potentials of space exploration, and we are on the cusp of a new era in space travel.</p><h2>New Horizons</h2><p>Advances in technology have made it possible to explore deeper into space than ever before. Spacecrafts are now capable of traveling to distant planets and moons, and we are learning more about our solar system and the universe every day.</p><h3>Challenges of Space Travel</h3><p>However, space travel is not without its challenges. It is a dangerous and expensive endeavor, and the harsh conditions of space can take a toll on both spacecrafts and the people who operate them. Additionally, the technology required to sustain human life in space is still in its infancy.</p><h2>The Future of Space Travel</h2><p>Despite these challenges, the future of space travel is bright. Private companies are investing in space technology, and international collaboration is increasing. We can expect to see more missions to Mars and other planets, as well as the development of sustainable space habitats for long-term space exploration.</p><h3>The Importance of Space Travel</h3><p>Space exploration not only allows us to learn more aboutafaoliaocolansances some cheaplyas with mattered<p>about our universe, but it also has practical benefits for humanity. For example, satellite technology is used for communication, navigation, and weather forecasting. In addition, research conducted in space has led to numerous technological advancements in fields such as medicine and materials science. </p> <p>As we continue to push the boundaries of space exploration, we will undoubtedly encounter new challenges and obstacles. However, the potential benefits of space travel make it an endeavor worth pursuing. We must continue to invest in the technology and infrastructure needed to make space travel more efficient, sustainable, and accessible. </p>",
    author: "Jane Smith",
    image: "/assets/ai-4.jpg",
    snippet: "Exploring Beyond our Planet Space travel has come a long way since the days of the first satellite launches and manned space missions. Today, we have a better understanding of the challenges and potentials of space exploration, and we are on the cusp of a new era in space travel. New Horizons Advances in technology have made it possible to ...",
  },
  {
    category: "Tech",
    title: "The Importance of Mental Health in the Workplace",
    content: "<h1>The Importance of <em>Mental Health</em> in the <strong>Workplace</strong></h1><p>The topic of mental health has become increasingly important in recent years, and the workplace is no exception. In fact, studies have shown that poor mental health can have a significant impact on productivity, morale, and overall job performance.</p><h2>Mental Health and Productivity</h2><p>Individuals who struggle with mental health issues such as anxiety and depression often have difficulty focusing and completing tasks. This can lead to decreased productivity and increased absenteeism. In contrast, individuals who are able to maintain good mental health are more likely to be engaged and productive employees.</p><h3>Creating a Supportive Workplace</h3><p>Creating a supportive and inclusive workplace can go a long way in promoting good mental health. This includes providing resources and support for employees who may be struggling with mental health issues, as well as educating managers and coworkers about mental health and how to support individuals who may be struggling.</p><h2>The Role of Employers</h2><p>Employers play a key role in promoting mental health in the workplace. This includes providing access to resources such as Employee Assistance Programs and mental health services, as well as creating a culture where mental health is openly discussed and supported. </p><h3>Breaking the Stigma</h3><p>It is also important to break the stigma surrounding mental health and create an environment where individuals feel comfortable seeking help. This can be done by providing education and training on mental health, promoting open and honest conversations about mental health, and creating a culture of understanding and acceptance.</p>",
    author: "Jane Smith",
    image: "/assets/ai-5.jpg",
    snippet: "The Importance of Mental Health in the Workplace The topic of mental health has become increasingly important in recent years, and the workplace is no exception. In fact, studies have shown that poor mental health can have a significant impact on productivity, morale, and overall job performance. Mental Health and Productivity Individuals w...",
  },
  {
    category: "Literature",
    title: "The Art of Storytelling: Exploring the Power of Literature",
    content: "<h1>The Art of Storytelling: Exploring the Power of Literature</h1><p>There is something truly magical about a great work of literature. Whether it's a novel, a poem, or a play, the power of a well-told story can transport us to other worlds, introduce us to fascinating characters, and challenge our perceptions of the world around us.</p><h2>The Importance of Literature</h2><p>Through literature, we can explore complex issues, grapple with the complexities of the human condition, and gain a deeper understanding of ourselves and others. Literature can also serve as a means of preserving history and culture, giving us a glimpse into the lives and experiences of people from different times and places.</p><h3>The Beauty of Words</h3><p>But literature is more than just a tool for learning and introspection. It can also be a thing of beauty in its own right. The power of language and the artistry of great writers can inspire us, move us, and leave us breathless.</p><h2>The Role of the Reader</h2><p>Of course, literature cannot exist in a vacuum. It requires readers to bring it to life, to engage with the story, and to find meaning in the words on the page. And in doing so, readers can discover new insights about themselves, the world, and the human experience.</p><h3>The Joys of Reading</h3><p>So whether you're a seasoned bibliophile or just discovering the joys of reading, take some time to explore the power of literature. You may be surprised at what you find.</p>",
    author: "Charlotte Dubois",
    image: "/assets/book-1.jpg",
    snippet: "The Art of Storytelling: Exploring the Power of Literature There is something truly magical about a great work of literature. Whether it's a novel, a poem, or a play, the power of a well-told story can transport us to other worlds, introduce us to fascinating characters, and challenge our perceptions of the world around us...",
  },
  {
    category: "Literature",
    title: "Uncovering the Mysteries of Gabriel Garcia Marquez's Magical Realism",
    content: `<h1>Uncovering the Mysteries of Gabriel Garcia Marquez's Magical Realism</h1><p>Gabriel Garcia Marquez is one of the most famous writers of the 20th century, known for his unique literary style that blends magical elements with reality. His novels and stories, including One Hundred Years of Solitude and Love in the Time of Cholera, have captivated readers all over the world.</p><h2>Magical Realism: A Literary Genre</h2><p>Magical realism is a literary genre that combines elements of fantasy and reality. It is characterized by a seamless blend of the fantastic and the ordinary, often in a way that challenges readers' perceptions of reality. </p><h3>The Origins of Magical Realism</h3><p>The term "magical realism" was first coined in the 1940s by the German art critic Franz Roh, who used it to describe a group of Latin American painters. The term was later applied to literature, specifically the works of Gabriel Garcia Marquez and other Latin American writers.</p><h2>The Legacy of Gabriel Garcia Marquez</h2><p>Gabriel Garcia Marquez's literary legacy is a rich and complex one. His use of magical realism has inspired countless writers and artists around the world, and his works continue to be read and studied today. </p><h3>One Hundred Years of Solitude</h3><p>One Hundred Years of Solitude, Garcia Marquez's most famous novel, tells the story of the Buendia family over the course of seven generations. The novel is a masterpiece of magical realism, blending fantastical elements with the history of Colombia and the Buendia family's own struggles and triumphs.</p><h3>Love in the Time of Cholera</h3><p>Love in the Time of Cholera is another one of Garcia Marquez's most famous works. The novel tells the story of a love triangle between Fermina Daza, Dr. Juvenal Urbino, and Florentino Ariza. Set in the Caribbean coast of Colombia, the novel explores themes of love, aging, and the passage of time.</p><h2>In Conclusion</h2><p>Gabriel Garcia Marquez's unique literary style has had a profound impact on the world of literature. His works have inspired countless writers and readers, and his use of magical realism has become a defining feature of Latin American literature. If you haven't yet had the chance to read his novels and stories, I highly recommend you do so.</p>`,
    author: "Lucie Martin",
    image: "/assets/book-1.jpg",
    snippet: "Uncovering the Mysteries of Gabriel Garcia Marquez's Magical Realism Gabriel Garcia Marquez is one of the most famous writers of the 20th century, known for his unique literary style that blends magical elements with reality. His novels and stories, including One Hundred Years of Solitude and Love in the Time of Cholera, have captivated readers...",
  },
  {
    category: "Literature",
    title: "The Art of Storytelling: Why Literature Matters",
    content: "<h1>The Art of Storytelling: Why Literature Matters</h1><p>Literature has been a fundamental aspect of human culture for centuries, and for good reason. Storytelling is an essential part of our lives and helps us make sense of the world around us. Whether it's a novel, a poem, or a play, literature has the power to transport us to new worlds, inspire us, and teach us valuable life lessons.</p><h2>The Power of Imagination</h2><p>Reading literature encourages us to use our imagination, which is essential for personal growth and development. It allows us to escape our daily routine and explore new perspectives and ideas.</p><h3>Emotional Intelligence</h3><p>Literature also helps us develop emotional intelligence, as it allows us to experience a range of emotions through the characters we read about. By empathizing with characters and their struggles, we learn to become more compassionate and understanding towards others in our own lives.</p><h2>The Importance of Diversity</h2><p>Reading literature from different cultures and backgrounds is crucial for developing empathy and understanding towards those who are different from us. It helps break down stereotypes and allows us to see the world from different perspectives.</p><h3>The Beauty of Language</h3><p>Lastly, literature is a celebration of language and the beauty of words. Through reading, we can appreciate the artistry of language and the power of words to convey complex emotions and ideas.</p>",
    author: "Eloise Martin",
    image: "/assets/literature-1.jpg",
    snippet: "The Art of Storytelling: Why Literature Matters Literature has been a fundamental aspect of human culture for centuries, and for good reason. Storytelling is an essential part of our lives and helps us make sense of the world around us. Whether it's a novel, a poem, or a play, literature has the power to transport us to new worlds, inspire us, and teach us valuable life lessons.",
  },
  {
    category: "Literature",
    title: "The Influence of Shakespeare on Modern Literature",
    content: "<h1>The Influence of Shakespeare on Modern Literature</h1><p>William Shakespeare is widely considered to be one of the greatest playwrights in history. His works, such as Romeo and Juliet and Hamlet, have had a profound impact on literature and continue to be studied and performed to this day.</p><h2>Shakespeare's Legacy</h2><p>Shakespeare's influence can be seen in many aspects of modern literature, from the themes explored in contemporary plays and novels to the language used by modern writers. His characters, such as Romeo and Juliet, have become archetypes that are still used in storytelling today.</p><h3>The Importance of Shakespeare</h3><p>Shakespeare's impact on literature cannot be overstated. His works have been translated into every major language and are studied in schools and universities around the world. They have inspired countless adaptations, from stage productions to films and television shows.</p><h2>Shakespeare's Continued Relevance</h2><p>Despite being written hundreds of years ago, Shakespeare's works continue to resonate with audiences today. His exploration of human nature and his ability to capture the complexities of the human experience make his plays and sonnets timeless works of art.</p><h3>A Lasting Legacy</h3><p>As we continue to explore the world of literature, it is impossible to overlook the influence of William Shakespeare. His works have shaped the literary landscape in ways that few other writers have been able to match, and his legacy will continue to inspire writers and readers for generations to come.</p>",
    author: "Sophie Martin",
    image: "/assets/literature-1.jpg",
    snippet: "The Influence of Shakespeare on Modern Literature William Shakespeare is widely considered to be one of the greatest playwrights in history. His works, such as Romeo and Juliet and Hamlet, have had a profound impact on literature and continue to be studied and performed to this day. Shakespeare's influence can be seen in many aspects of modern...",
  },
  {
    category: "Philosophy",
    title: "The Importance of Self-Reflection in Philosophy",
    content: "<h1>The Importance of Self-Reflection in Philosophy</h1><p>Philosophy is a discipline that requires critical thinking, analysis, and reflection. Self-reflection is an essential part of philosophy that enables individuals to understand themselves, their beliefs, and their values. In this blog post, we will explore the importance of self-reflection in philosophy.</p><h2>Understanding Your Beliefs and Values</h2><p>Self-reflection allows individuals to examine their beliefs and values critically. By doing so, they can gain a better understanding of their thought processes, biases, and assumptions. This understanding can help individuals to refine their beliefs and values, and to develop more informed and nuanced perspectives.</p><h3>Developing Critical Thinking Skills</h3><p>Self-reflection is an important tool for developing critical thinking skills. By examining our thoughts and beliefs, we can learn to identify flaws in our reasoning and arguments. This process helps us to develop more logical, well-reasoned positions and arguments.</p><h2>Improving Personal Growth and Development</h2><p>Self-reflection is a valuable tool for personal growth and development. By examining our beliefs, values, and assumptions, we can identify areas where we need to grow and improve. This process allows us to become more self-aware and to develop a deeper understanding of ourselves.</p><h3>Conclusion</h3><p>Self-reflection is an essential component of philosophy. It enables individuals to examine their beliefs and values critically, develop critical thinking skills, and improve personal growth and development. By incorporating self-reflection into our philosophical practices, we can become better thinkers and more fully realized individuals.</p>",
    author: "Johann Schmidt",
    image: "/assets/philosophy-1.jpg",
    snippet: "The Importance of Self-Reflection in Philosophy Philosophy is a discipline that requires critical thinking, analysis, and reflection. Self-reflection is an essential part of philosophy that enables individuals to understand themselves, their beliefs, and their values. In this blog post, we will explore the importance of self-reflection in philosophy.",
  },
  {
    category: "Travel",
    title: "The Best Places to Visit in Europe for Nature Lovers",
    content:
      "<h1>Nature in Europe: <i>Discovering the Beauty</i></h1><p>Europe is home to some of the most beautiful and diverse natural landscapes in the world. From the majestic Alps to the rugged coastlines of Scotland, there is something for every nature lover to enjoy. In this article, we will take a look at some of the best places to visit in Europe for nature enthusiasts.</p><h2>Switzerland</h2><p>Switzerland is a nature lover's paradise. The country is home to majestic mountains, crystal clear lakes, and picturesque villages. The Swiss Alps are a must-see for any nature lover, with peaks such as the Matterhorn and Eiger offering breathtaking views. In addition, Switzerland is home to several national parks, including the Jungfrau-Aletsch which is a UNESCO World Heritage Site. </p><h2>Scotland</h2><p>Scotland is a land of rugged beauty and natural wonder. From the misty highlands to the rolling hills of the countryside, Scotland offers a wealth of natural landscapes to explore. The Isle of Skye is a particular highlight, with its dramatic cliffs and rugged coastline. In addition, Scotland is home to several national parks, including the Cairngorms National Park, which is home to a wide variety of wildlife, including red deer and golden eagles.</p><h2>Norway</h2><p>Norway is a country of extraordinary natural beauty, with fjords, mountains, and waterfalls. The Norwegian fjords are a must-see for any nature lover, with the famous Geirangerfjord and Nærøyfjord offering spectacular views. In addition, Norway is home to several national parks, including Jotunheimen National Park, which is home to some of the highest mountains in Northern Europe. </p><h2>Conclusion</h2><p>Europe is home to some of the most beautiful and diverse natural landscapes in the world, and these are just a few examples of the many places worth visiting. Whether you're a hiker, a bird watcher, or just someone who enjoys the beauty of nature, Europe has something for everyone. </p>",
    author: "Jane Smith",
    image: "/assets/vacation-5.jpg",
    snippet: "Nature in Europe: Discovering the Beauty Europe is home to some of the most beautiful and diverse natural landscapes in the world. From the majestic Alps to the rugged coastlines of Scotland, there is something for every nature lover to enjoy. In this article, we will take a look at some of the best places to visit in Europe for nature enthusia...",
  },
  {
    category: "Psychology",
    title: "The Psychology Behind Self-Esteem and its Impact on Well-Being",
    content:
      "<h1>The Psychology Behind Self-Esteem and its Impact on Well-Being</h1><p>Self-esteem is an essential component of our psychological well-being. It is the belief we hold about ourselves and our abilities. It is the confidence we have in our own worth and the value we place on ourselves. High self-esteem is associated with positive psychological outcomes such as happiness, life satisfaction, and mental well-being.</p><h2>The Importance of Self-Esteem</h2><p>Self-esteem influences how we perceive ourselves, others, and the world around us. It impacts our behavior, emotions, and thoughts. People with high self-esteem are more likely to take risks, pursue their goals, and have fulfilling relationships. They are also more resilient in the face of adversity and better able to cope with stress.</p><h3>The Psychology of Self-Esteem</h3><p>Self-esteem is formed through our experiences and interactions with others. It is influenced by our upbringing, culture, and social environment. Our self-esteem can fluctuate depending on the situation, and it can be improved through personal growth and positive experiences.</p><h2>The Impact of Low Self-Esteem</h2><p>Low self-esteem is associated with negative psychological outcomes such as depression, anxiety, and poor self-image. It can lead to self-destructive behaviors such as substance abuse and disordered eating. It can also impact our relationships and our ability to achieve our goals.</p><h3>Building Self-Esteem</h3><p>There are many ways to build self-esteem, such as setting achievable goals, practicing self-compassion, and seeking social support. Therapy can also be an effective way to address underlying issues that contribute to low self-esteem.</p><h2>Conclusion</h2><p>Self-esteem is an essential component of our psychological well-being. It impacts how we think, feel, and behave. By understanding the psychology behind self-esteem, we can take steps to improve our own self-esteem and promote well-being in ourselves and others.</p>",
    author: "Gabriella Russo",
    image: "/assets/self-esteem.jpg",
    snippet: "The Psychology Behind Self-Esteem and its Impact on Well-Being Self-esteem is an essential component of our psychological well-being. It is the belief we hold about ourselves and our abilities. It is the confidence we have in our own worth and the value we place on ourselves. High self-esteem is associated with positive psychological outcomes such as happiness, life satisfaction, and mental well-being.",
  },
  {
    category: "Business",
    title: "The Impact of Layoffs on Employee Morale and Productivity",
    content:
      "<h1>The <strong>Impact</strong> of Layoffs on <em>Employee Morale</em> and Productivity</h1><p>Layoffs, also known as downsizing, is a common business strategy used to cut costs and improve a company's bottom line. However, layoffs can have a significant impact on the remaining employees, both in terms of morale and productivity.</p><h2>Decrease in Employee Morale</h2><p>When a company lays off employees, it can create feelings of insecurity and uncertainty among the remaining staff. The remaining employees may worry about their own job security and may also feel guilty for not being affected by the layoffs. This can lead to a decrease in employee morale and an increase in stress levels.</p><h3>Decrease in Productivity</h3><p>In addition to a decrease in employee morale, layoffs can also lead to a decrease in productivity. With fewer employees, remaining staff may be asked to take on additional responsibilities, which can lead to burnout and fatigue. Additionally, the loss of experienced and skilled employees can lead to a decrease in the overall knowledge and expertise of the company.</p><h2>Mitigating the Impact of Layoffs</h2><p>To mitigate the negative impact of layoffs, companies can take steps such as providing support and resources for the remaining employees, clearly communicating the reasons for the layoffs, and offering opportunities for skill development and career advancement.</p><h3>Conclusion</h3><p>While layoffs may be necessary for a company's financial stability, it is important to consider the impact they can have on employee morale and productivity. By taking steps to mitigate the negative effects, companies can help to ensure that the remaining employees remain engaged and productive.</p>",
    author: "Jane Doe",
    image: "/assets/layoffs-3.jpg",
    snippet: "The Impact of Layoffs on Employee Morale and Productivity Layoffs, also known as downsizing, is a common business strategy used to cut costs and improve a company's bottom line. However, layoffs can have a significant impact on the remaining employees, both in terms of morale and productivity. Decrease in Employee Morale When a company lays...",
  },
];

async function main() {
  console.log(`Start seeding...`);
  for (const post of posts) {
    await prisma.post.create({ data: post });
  }
  console.log(`Seeding finished.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
